server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hcute-security?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
  session:
    store-type: none
# 配置时间返回为时间戳 springboot 1.0版本是默认的，但是springboot 2.0 版本是需要配置的
  jackson:
    serialization:
      write-dates-as-timestamps: true

# 配置时间戳返回的格式
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss

# 登录页面可配置
#hcute:
#  security:
#    browser:
#      loginPage: /demo-signIn.html

# 登录成功或失败的提示方式可配置
#hcute:
#  security:
#    browser:
#      loginType: REDIRECT

# 图形验证码可配置
#hcute:
#  security:
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user,/user/*
